

_: compile run1 clean

2: compile run2 clean

compile:
	javac *.java

run2: 
	java test		#todas las opciones por parte del usuario

run1: 
	java finala		#algunas opc por prog y las otras por usuario

clean:
	rm *.class