

_: compile run1 clean

2: compile run2 clean

compile:
	javac *.java

run1: 
	java test		#todas las opciones por parte del usuario

run2: 
	java tesv2		#algunas opc por prog y las otras por usuario

clean:
	rm *.class